#define IO_STDIO 1
#define IO_SDL 0

#define RENDER_BORDERS 1
#define RENDER_TEXTURES 0

#define TRANSPARENT_TEXTURES 0

#define ANIMATED_TEXTURES 0

#define RENDER_SPRITES 0
#define ANIMATIED_SPRITES 0

#define RENDER_BG_SOLID 1
#define RENDER_BG_IMAGE 0

#define CHECK_COLLISIONS 0

#define INTERACTIVE_OBJECTS 0


